import "../app/globals.css"
import { Layout } from "../../components"
import { StateContext } from "../../context/StateContext"
import { Toaster } from "react-hot-toast"
export const metadata = {
  title: 'Deap Shopping Center',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
       <StateContext>
        <Layout>
          <Toaster/>
          {children}
          </Layout>
          </StateContext>
        </body>
    </html>
  )
}
